//! Le Mans Ultimate shared memory: the `LMU_Data` mapping the game publishes
//! itself (Settings > Gameplay > Enable Plugins, then a restart).
//!
//! # Where these offsets come from
//!
//! S397 ships the C++ headers with the game (`Support\SharedMemoryInterface`)
//! but their licence forbids redistribution, so the header is **not vendored**
//! here. Every constant below was produced by compiling the shipped header
//! locally with MSVC and printing `sizeof`/`offsetof` (see
//! `docs/lmu-shared-memory.md`), then cross-checked against TinyPedal's
//! `pyLMUSharedMemory` (MIT), which transcribes the same header into ctypes.
//! `tests/lmu_shm_layout.rs` pins every number against a golden byte dump
//! generated by that same compiled header — if S397 moves a field, it fails.
//!
//! # Two packings in one mapping
//!
//! `InternalsPlugin.hpp` wraps its structs in `#pragma pack(push, 4)`, so
//! `TelemInfoV01` and friends are 4-byte packed. The `SharedMemory*` wrappers
//! in `SharedMemoryInterface.hpp` are declared *after* the matching `pop`, so
//! they use default alignment. Mixing the two up silently shifts every offset,
//! which is why the wrapper layout lives here as arithmetic constants with
//! their own asserts rather than as more packed structs.
//!
//! # The portable half and the Windows half (issue #35)
//!
//! Everything in this file is plain data work — sizes, offsets, decode
//! helpers, a snapshot — with no OS in it, so it builds and tests on any
//! host, and `tests/lmu_shm_layout.rs` pins the numbers against the golden
//! dump from Linux CI as well as Windows. The reader itself cannot be
//! portable: it opens win32 **named kernel objects** (the `LMU_Data`
//! section, the data event, the lock section and its event), and Proton
//! does not bridge those into the Linux namespace — so even with the game
//! running under Proton on Linux there is nothing for a native process to
//! open. That half lives in [`shm_win`](self::win), compiled only on
//! Windows and re-exported from here so the existing
//! `lmu::shm::{Reader, Wake}` path keeps working. On non-Windows those two
//! items simply don't exist, and `Lmu::start` answers
//! [`crate::Error::LmuNotRunning`] (see `lmu.rs`).

// The Windows half: kernel32 FFI, the process scan, the game's lock and the
// `Reader`. `#[path]` because a bare `mod shm_win;` here would resolve under
// `lmu/shm/`; the attribute keeps the file beside this one, where the issue
// #35 split put it. Gated out entirely on other hosts — a cfg-stripped module
// is never even resolved, so no Linux build ever sees a kernel32 import.
#[cfg(windows)]
#[path = "shm_win.rs"]
mod win;

// Re-exported so existing callers keep using `lmu::shm::Reader` /
// `lmu::shm::Wake` exactly as before the split: the module path is public API,
// the inner module is an implementation detail.
#[cfg(windows)]
pub use win::{Reader, Wake};

/// The process name the game runs under. Matched case-insensitively by the
/// Windows reader's process scan (see `shm_win.rs`); a transcription fact, so
/// it lives with the rest of the layout rather than in the reader.
pub const GAME_EXE: &str = "Le Mans Ultimate.exe";

// ------------------------------------------------------------ wrapper layout

/// `sizeof(SharedMemoryLayout)`. Four bytes larger than the sum of its parts:
/// the trailing padding that default alignment adds for the 8-byte `size_t`
/// inside `SharedMemoryScoringData`.
pub const LAYOUT_SIZE: usize = 324_824;
/// `offsetof(SharedMemoryObjectOut, scoring)` — i.e. `sizeof(generic) + sizeof(paths)`.
pub const OFF_SCORING: usize = 1_632;
/// `offsetof(SharedMemoryObjectOut, telemetry)`.
pub const OFF_TELEMETRY: usize = 128_464;
const SCORING_SIZE: usize = 126_832;
/// `offsetof(SharedMemoryScoringData, vehScoringInfo)` — 548 bytes of
/// `ScoringInfoV01`, 4 of alignment padding, then the 8-byte `scoringStreamSize`.
pub const OFF_VEH_ARRAY: usize = 560;
/// `offsetof(SharedMemoryTelemetryData, telemInfo)`; the three leading `u8`s
/// are followed by one byte of padding.
pub const OFF_TELEM_ARRAY: usize = 4;
// The two flag offsets below (and `SCORING_INFO_SIZE` further down) are
// consumed only by the Windows reader's memcpy in `shm_win.rs`, so they are
// gated with it — on a non-Windows build nothing reaches them, and dead
// private constants would fail the `-D warnings` lint. The values themselves
// are transcription facts like every other constant in this section.
#[cfg(windows)]
const OFF_ACTIVE_VEHICLES: usize = 0;
#[cfg(windows)]
const OFF_PLAYER_IDX: usize = 1;
/// The fixed array bound in both payloads. A larger `mNumVehicles` than this
/// would mean a header change; we clamp rather than read past the array.
pub const MAX_VEHICLES: usize = 104;

// The wrappers are arithmetic rather than structs (nothing in them needs
// naming), so their "size asserts" are the relations between the constants.
const _: () = assert!(OFF_TELEMETRY == OFF_SCORING + SCORING_SIZE);
const _: () = assert!(SCORING_SIZE == OFF_VEH_ARRAY + MAX_VEHICLES * VEH_SIZE + 65_536);
const _: () =
    assert!(LAYOUT_SIZE == OFF_TELEMETRY + OFF_TELEM_ARRAY + MAX_VEHICLES * TELEM_SIZE + 4);

const TELEM_SIZE: usize = std::mem::size_of::<TelemInfoV01>();
const VEH_SIZE: usize = std::mem::size_of::<VehicleScoringInfoV01>();
// Gated with the reader, same reason as the two offsets above.
#[cfg(windows)]
const SCORING_INFO_SIZE: usize = std::mem::size_of::<ScoringInfoV01>();

// --------------------------------------------------------- packed transcript

/// `TelemWheelV01`. Corner order across all four-element arrays is **FL, FR,
/// RL, RR**, per the header's own comment on `mWheel[4]`.
#[repr(C, packed(4))]
#[derive(Clone, Copy)]
pub struct TelemWheelV01 {
    _pad0: [u8; 24],
    /// **Kelvin**, despite the header commenting it as Celsius. Measured
    /// 2026-09-07 against a live session: a cold car in the garage reads
    /// 293.18 (ambient 20 °C, not 293 °C) and rises to ~873 under braking.
    /// The comment is wrong; the data is not.
    pub m_brake_temp: f64,
    _pad32: [u8; 88],
    /// kPa.
    pub m_pressure: f64,
    /// Kelvin, sampled left / centre / right across the tread. Reads a flat
    /// 0.0 — not ambient — until the car has been on track, so zero means
    /// "not populated yet", never "absolute zero".
    pub m_temperature: [f64; 3],
    /// Tyre **life remaining**, 1.0 fresh falling toward 0 — *not* wear, in
    /// spite of the field name and the header's "wear (0.0-1.0, fraction of
    /// maximum)". Measured over a five-lap stint: 1.0 → 0.933. Same direction
    /// as the REST `wearables.tires`, so reading it as wear inverts every
    /// alert.
    pub m_wear: f64,
    _pad160: [u8; 44],
    /// Kelvin.
    pub m_tire_carcass_temperature: f64,
    _pad212: [u8; 48],
}

/// `TelemInfoV01` — the player's 100 Hz channel feed.
#[repr(C, packed(4))]
#[derive(Clone, Copy)]
pub struct TelemInfoV01 {
    pub m_id: i32,
    pub m_delta_time: f64,
    pub m_elapsed_time: f64,
    pub m_lap_number: i32,
    pub m_lap_start_et: f64,
    _pad32: [u8; 128],
    pub m_pos: [f64; 3],
    /// Local vehicle coordinates: **+x out the left side, +y up, +z out the
    /// back**. Forward speed is therefore `-z`, not `+z`.
    pub m_local_vel: [f64; 3],
    /// Same frame as `m_local_vel`, m/s².
    pub m_local_accel: [f64; 3],
    _pad232: [u8; 120],
    /// -1 reverse, 0 neutral, 1+ forward.
    pub m_gear: i32,
    pub m_engine_rpm: f64,
    _pad364: [u8; 24],
    pub m_unfiltered_throttle: f64,
    pub m_unfiltered_brake: f64,
    /// -1.0 (full left) to 1.0 (full right).
    pub m_unfiltered_steering: f64,
    _pad412: [u8; 112],
    /// Litres.
    pub m_fuel: f64,
    pub m_engine_max_rpm: f64,
    _pad540: [u8; 60],
    /// Zero-based, with the pit lane stored in the sign bit.
    pub m_current_sector: i32,
    _pad604: [u8; 4],
    /// Litres.
    pub m_fuel_capacity: f64,
    _pad616: [u8; 129],
    pub m_lap_invalidated: u8,
    _pad746: [u8; 30],
    /// LMU extension, `f32` not `f64`: remaining virtual energy as a fraction.
    pub m_virtual_energy: f32,
    /// LMU extension: seconds to the car ahead on track, published per frame.
    pub m_time_gap_car_ahead: f32,
    /// LMU extension: seconds to the car behind on track.
    pub m_time_gap_car_behind: f32,
    _pad788: [u8; 60],
    /// FL, FR, RL, RR.
    pub m_wheel: [TelemWheelV01; 4],
}

/// `VehicleScoringInfoV01` — one per car, 5 Hz.
#[repr(C, packed(4))]
#[derive(Clone, Copy)]
pub struct VehicleScoringInfoV01 {
    pub m_id: i32,
    pub m_driver_name: [u8; 32],
    pub m_vehicle_name: [u8; 64],
    pub m_total_laps: i16,
    /// 0 = sector 3 (start/finish), 1 = sector 1, 2 = sector 2.
    pub m_sector: i8,
    _pad103: [u8; 1],
    /// Metres travelled along the lap.
    pub m_lap_dist: f64,
    _pad112: [u8; 32],
    pub m_best_lap_time: f64,
    _pad152: [u8; 16],
    pub m_last_lap_time: f64,
    _pad176: [u8; 20],
    pub m_is_player: u8,
    _pad197: [u8; 1],
    pub m_in_pits: u8,
    /// 1-based overall position.
    pub m_place: u8,
    pub m_vehicle_class: [u8; 32],
    pub m_time_behind_next: f64,
    pub m_laps_behind_next: i32,
    pub m_time_behind_leader: f64,
    pub m_laps_behind_leader: i32,
    _pad256: [u8; 208],
    pub m_time_into_lap: f64,
    pub m_estimated_lap_time: f64,
    _pad480: [u8; 104],
}

/// `ScoringInfoV01` — the session header that precedes the per-car array.
#[repr(C, packed(4))]
#[derive(Clone, Copy)]
pub struct ScoringInfoV01 {
    pub m_track_name: [u8; 64],
    pub m_session: i32,
    pub m_current_et: f64,
    pub m_end_et: f64,
    pub m_max_laps: i32,
    /// **Track length in metres** — the denominator for normalised track
    /// position. Note the name collides with the per-car `m_lap_dist`, which
    /// is progress *along* this.
    pub m_lap_dist: f64,
    _pad96: [u8; 8],
    pub m_num_vehicles: i32,
    pub m_game_phase: u8,
    _pad109: [u8; 439],
}

// Sizes are the load-bearing part of the transcription: if a pad is wrong, the
// struct is the wrong size and this fails at compile time rather than silently
// decoding garbage in a race.
const _: () = assert!(std::mem::size_of::<TelemWheelV01>() == 260);
const _: () = assert!(std::mem::size_of::<TelemInfoV01>() == 1_888);
const _: () = assert!(std::mem::size_of::<VehicleScoringInfoV01>() == 584);
const _: () = assert!(std::mem::size_of::<ScoringInfoV01>() == 548);

/// Decode one transcribed struct out of a byte buffer at `offset`.
///
/// The reader itself copies straight from the mapping; this is how a byte dump
/// (the golden layout fixture, or a future capture) is read back through the
/// same transcription.
pub fn read_struct<T: Copy>(bytes: &[u8], offset: usize) -> Option<T> {
    let size = std::mem::size_of::<T>();
    let end = offset.checked_add(size)?;
    if end > bytes.len() {
        return None;
    }
    // SAFETY: bounds are checked above, `T: Copy` is one of the packed
    // transcripts (plain old data, no invalid bit patterns, alignment 4 or
    // less), and the read is unaligned so an arbitrary offset is fine.
    Some(unsafe { bytes.as_ptr().add(offset).cast::<T>().read_unaligned() })
}

/// Trim a fixed-width C string field to a `String`.
pub fn c_str(bytes: &[u8]) -> String {
    let end = bytes.iter().position(|&b| b == 0).unwrap_or(bytes.len());
    String::from_utf8_lossy(&bytes[..end]).into_owned()
}

// -------------------------------------------------------------- the reader

/// One decimated copy of the parts of the mapping we use.
pub struct Snapshot {
    pub telem: TelemInfoV01,
    pub scoring: ScoringInfoV01,
    /// Only the first `num_vehicles` entries are populated.
    pub vehicles: Vec<VehicleScoringInfoV01>,
    pub num_vehicles: usize,
    pub player_idx: usize,
    pub player_has_vehicle: bool,
}

impl Snapshot {
    /// Assemble a snapshot from already-decoded parts — how a replay or a
    /// layout test builds one without a running game.
    pub fn from_parts(
        telem: TelemInfoV01,
        scoring: ScoringInfoV01,
        vehicles: Vec<VehicleScoringInfoV01>,
    ) -> Self {
        let num_vehicles = vehicles.len().min(MAX_VEHICLES);
        let mut all = vehicles;
        all.resize(MAX_VEHICLES, unsafe { std::mem::zeroed() });
        Snapshot {
            telem,
            scoring,
            vehicles: all,
            num_vehicles,
            player_idx: 0,
            player_has_vehicle: num_vehicles > 0,
        }
    }

    /// A zeroed snapshot: the starting state of the Windows reader's
    /// preallocated buffers. Only `shm_win::Reader` assembles live snapshots,
    /// so this is gated with the reader — [`Snapshot::from_parts`] is the
    /// portable, tested construction path.
    #[cfg(windows)]
    fn new() -> Self {
        Snapshot {
            // SAFETY: both are plain old data with no padding invariants and no
            // Drop; all-zero is a valid (if meaningless) bit pattern, and every
            // field is overwritten before the snapshot is read.
            telem: unsafe { std::mem::zeroed() },
            scoring: unsafe { std::mem::zeroed() },
            vehicles: vec![unsafe { std::mem::zeroed() }; MAX_VEHICLES],
            num_vehicles: 0,
            player_idx: 0,
            player_has_vehicle: false,
        }
    }

    /// The player's scoring row, matched by the telemetry slot id rather than
    /// by index: the two arrays are written by different subsystems and are not
    /// guaranteed to be in the same order.
    pub fn player_scoring(&self) -> Option<&VehicleScoringInfoV01> {
        let id = self.telem.m_id;
        self.vehicles[..self.num_vehicles]
            .iter()
            .find(|v| v.m_id == id)
            .or_else(|| {
                self.vehicles[..self.num_vehicles]
                    .iter()
                    .find(|v| v.m_is_player != 0)
            })
    }

    pub fn vehicles(&self) -> &[VehicleScoringInfoV01] {
        &self.vehicles[..self.num_vehicles]
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn c_str_stops_at_the_nul_not_the_end_of_the_field() {
        let mut field = [0u8; 32];
        field[..4].copy_from_slice(b"LMP3");
        field[10] = b'X'; // garbage past the terminator, as real fields carry
        assert_eq!(c_str(&field), "LMP3");
    }

    #[test]
    fn a_field_with_no_terminator_still_decodes() {
        assert_eq!(c_str(&[b'a'; 4]), "aaaa");
    }
}
