//! Le Mans Ultimate shared memory: the `LMU_Data` mapping the game publishes
//! itself (Settings > Gameplay > Enable Plugins, then a restart).
//!
//! # Where these offsets come from
//!
//! S397 ships the C++ headers with the game (`Support\SharedMemoryInterface`)
//! but their licence forbids redistribution, so the header is **not vendored**
//! here. Every constant below was produced by compiling the shipped header
//! locally with MSVC and printing `sizeof`/`offsetof` (see
//! `docs/lmu-shared-memory.md`), then cross-checked against TinyPedal's
//! `pyLMUSharedMemory` (MIT), which transcribes the same header into ctypes.
//! `tests/lmu_shm_layout.rs` pins every number against a golden byte dump
//! generated by that same compiled header — if S397 moves a field, it fails.
//!
//! # Two packings in one mapping
//!
//! `InternalsPlugin.hpp` wraps its structs in `#pragma pack(push, 4)`, so
//! `TelemInfoV01` and friends are 4-byte packed. The `SharedMemory*` wrappers
//! in `SharedMemoryInterface.hpp` are declared *after* the matching `pop`, so
//! they use default alignment. Mixing the two up silently shifts every offset,
//! which is why the wrapper layout lives here as arithmetic constants with
//! their own asserts rather than as more packed structs.

use std::ffi::c_void;
use std::sync::atomic::{AtomicI32, Ordering};
use std::time::{Duration, Instant};

use crate::{Error, Result};

// ---------------------------------------------------------------- win32 ffi

type Handle = *mut c_void;
type Bool32 = i32;

const INVALID_HANDLE_VALUE: Handle = -1isize as Handle;
const FILE_MAP_READ: u32 = 0x0004;
const FILE_MAP_ALL_ACCESS: u32 = 0x000F_001F;
const PAGE_READWRITE: u32 = 0x04;
const SYNCHRONIZE: u32 = 0x0010_0000;
const WAIT_OBJECT_0: u32 = 0;
const WAIT_TIMEOUT: u32 = 0x0000_0102;
const ERROR_ALREADY_EXISTS: u32 = 183;
const INFINITE: u32 = 0xFFFF_FFFF;
const TH32CS_SNAPPROCESS: u32 = 0x0000_0002;
const MAX_PROCESS_NAME: usize = 260;

// ponytail: raw kernel32 declarations rather than the `windows` crate — this is
// the entire Win32 surface we need, and it costs no dependency.
#[link(name = "kernel32")]
extern "system" {
    fn OpenFileMappingW(access: u32, inherit: Bool32, name: *const u16) -> Handle;
    fn CreateFileMappingW(
        file: Handle,
        attrs: *mut c_void,
        protect: u32,
        size_high: u32,
        size_low: u32,
        name: *const u16,
    ) -> Handle;
    fn MapViewOfFile(
        map: Handle,
        access: u32,
        off_high: u32,
        off_low: u32,
        len: usize,
    ) -> *mut c_void;
    fn UnmapViewOfFile(addr: *const c_void) -> Bool32;
    fn OpenEventW(access: u32, inherit: Bool32, name: *const u16) -> Handle;
    fn CreateEventW(
        attrs: *mut c_void,
        manual: Bool32,
        initial: Bool32,
        name: *const u16,
    ) -> Handle;
    fn SetEvent(event: Handle) -> Bool32;
    fn WaitForSingleObject(handle: Handle, millis: u32) -> u32;
    fn WaitForMultipleObjects(count: u32, handles: *const Handle, all: Bool32, millis: u32) -> u32;
    fn OpenProcess(access: u32, inherit: Bool32, pid: u32) -> Handle;
    fn CloseHandle(handle: Handle) -> Bool32;
    fn GetLastError() -> u32;
    fn CreateToolhelp32Snapshot(flags: u32, pid: u32) -> Handle;
    fn Process32FirstW(snapshot: Handle, entry: *mut ProcessEntry32W) -> Bool32;
    fn Process32NextW(snapshot: Handle, entry: *mut ProcessEntry32W) -> Bool32;
}

#[repr(C)]
struct ProcessEntry32W {
    size: u32,
    usage: u32,
    process_id: u32,
    default_heap_id: usize,
    module_id: u32,
    threads: u32,
    parent_process_id: u32,
    pri_class_base: i32,
    flags: u32,
    exe_file: [u16; MAX_PROCESS_NAME],
}

/// A Win32 handle that closes itself. Every handle in this module is owned by
/// one of these — teardown is otherwise very easy to get wrong on the error
/// paths, and a leaked mapping handle keeps the section alive after the game
/// exits.
struct OwnedHandle(Handle);

impl Drop for OwnedHandle {
    fn drop(&mut self) {
        if !self.0.is_null() {
            unsafe { CloseHandle(self.0) };
        }
    }
}

/// A mapped view that unmaps itself.
struct MappedView {
    addr: *mut c_void,
    len: usize,
}

impl Drop for MappedView {
    fn drop(&mut self) {
        if !self.addr.is_null() {
            unsafe { UnmapViewOfFile(self.addr) };
        }
    }
}

fn wide(s: &str) -> Vec<u16> {
    s.encode_utf16().chain(std::iter::once(0)).collect()
}

/// The PID of the running game, or `None` if it isn't up.
fn find_game_pid() -> Option<u32> {
    let snapshot = OwnedHandle(unsafe { CreateToolhelp32Snapshot(TH32CS_SNAPPROCESS, 0) });
    if snapshot.0.is_null() || snapshot.0 == INVALID_HANDLE_VALUE {
        return None;
    }
    let mut entry = ProcessEntry32W {
        size: std::mem::size_of::<ProcessEntry32W>() as u32,
        usage: 0,
        process_id: 0,
        default_heap_id: 0,
        module_id: 0,
        threads: 0,
        parent_process_id: 0,
        pri_class_base: 0,
        flags: 0,
        exe_file: [0; MAX_PROCESS_NAME],
    };
    let mut ok = unsafe { Process32FirstW(snapshot.0, &mut entry) };
    while ok != 0 {
        let end = entry.exe_file.iter().position(|&c| c == 0).unwrap_or(0);
        let name = String::from_utf16_lossy(&entry.exe_file[..end]);
        if name.eq_ignore_ascii_case(GAME_EXE) {
            return Some(entry.process_id);
        }
        ok = unsafe { Process32NextW(snapshot.0, &mut entry) };
    }
    None
}

pub const GAME_EXE: &str = "Le Mans Ultimate.exe";
const MAP_NAME: &str = "LMU_Data";
const DATA_EVENT_NAME: &str = "LMU_Data_Event";
const LOCK_MAP_NAME: &str = "LMU_SharedMemoryLockData";
const LOCK_EVENT_NAME: &str = "LMU_SharedMemoryLockEvent";

// ------------------------------------------------------------ wrapper layout

/// `sizeof(SharedMemoryLayout)`. Four bytes larger than the sum of its parts:
/// the trailing padding that default alignment adds for the 8-byte `size_t`
/// inside `SharedMemoryScoringData`.
pub const LAYOUT_SIZE: usize = 324_824;
/// `offsetof(SharedMemoryObjectOut, scoring)` — i.e. `sizeof(generic) + sizeof(paths)`.
pub const OFF_SCORING: usize = 1_632;
/// `offsetof(SharedMemoryObjectOut, telemetry)`.
pub const OFF_TELEMETRY: usize = 128_464;
const SCORING_SIZE: usize = 126_832;
/// `offsetof(SharedMemoryScoringData, vehScoringInfo)` — 548 bytes of
/// `ScoringInfoV01`, 4 of alignment padding, then the 8-byte `scoringStreamSize`.
pub const OFF_VEH_ARRAY: usize = 560;
/// `offsetof(SharedMemoryTelemetryData, telemInfo)`; the three leading `u8`s
/// are followed by one byte of padding.
pub const OFF_TELEM_ARRAY: usize = 4;
const OFF_ACTIVE_VEHICLES: usize = 0;
const OFF_PLAYER_IDX: usize = 1;
/// The fixed array bound in both payloads. A larger `mNumVehicles` than this
/// would mean a header change; we clamp rather than read past the array.
pub const MAX_VEHICLES: usize = 104;

// The wrappers are arithmetic rather than structs (nothing in them needs
// naming), so their "size asserts" are the relations between the constants.
const _: () = assert!(OFF_TELEMETRY == OFF_SCORING + SCORING_SIZE);
const _: () = assert!(SCORING_SIZE == OFF_VEH_ARRAY + MAX_VEHICLES * VEH_SIZE + 65_536);
const _: () =
    assert!(LAYOUT_SIZE == OFF_TELEMETRY + OFF_TELEM_ARRAY + MAX_VEHICLES * TELEM_SIZE + 4);

const TELEM_SIZE: usize = std::mem::size_of::<TelemInfoV01>();
const VEH_SIZE: usize = std::mem::size_of::<VehicleScoringInfoV01>();
const SCORING_INFO_SIZE: usize = std::mem::size_of::<ScoringInfoV01>();

// --------------------------------------------------------- packed transcript

/// `TelemWheelV01`. Corner order across all four-element arrays is **FL, FR,
/// RL, RR**, per the header's own comment on `mWheel[4]`.
#[repr(C, packed(4))]
#[derive(Clone, Copy)]
pub struct TelemWheelV01 {
    _pad0: [u8; 24],
    /// **Kelvin**, despite the header commenting it as Celsius. Measured
    /// 2026-09-07 against a live session: a cold car in the garage reads
    /// 293.18 (ambient 20 °C, not 293 °C) and rises to ~873 under braking.
    /// The comment is wrong; the data is not.
    pub m_brake_temp: f64,
    _pad32: [u8; 88],
    /// kPa.
    pub m_pressure: f64,
    /// Kelvin, sampled left / centre / right across the tread. Reads a flat
    /// 0.0 — not ambient — until the car has been on track, so zero means
    /// "not populated yet", never "absolute zero".
    pub m_temperature: [f64; 3],
    /// Tyre **life remaining**, 1.0 fresh falling toward 0 — *not* wear, in
    /// spite of the field name and the header's "wear (0.0-1.0, fraction of
    /// maximum)". Measured over a five-lap stint: 1.0 → 0.933. Same direction
    /// as the REST `wearables.tires`, so reading it as wear inverts every
    /// alert.
    pub m_wear: f64,
    _pad160: [u8; 44],
    /// Kelvin.
    pub m_tire_carcass_temperature: f64,
    _pad212: [u8; 48],
}

/// `TelemInfoV01` — the player's 100 Hz channel feed.
#[repr(C, packed(4))]
#[derive(Clone, Copy)]
pub struct TelemInfoV01 {
    pub m_id: i32,
    pub m_delta_time: f64,
    pub m_elapsed_time: f64,
    pub m_lap_number: i32,
    pub m_lap_start_et: f64,
    _pad32: [u8; 128],
    pub m_pos: [f64; 3],
    /// Local vehicle coordinates: **+x out the left side, +y up, +z out the
    /// back**. Forward speed is therefore `-z`, not `+z`.
    pub m_local_vel: [f64; 3],
    /// Same frame as `m_local_vel`, m/s².
    pub m_local_accel: [f64; 3],
    _pad232: [u8; 120],
    /// -1 reverse, 0 neutral, 1+ forward.
    pub m_gear: i32,
    pub m_engine_rpm: f64,
    _pad364: [u8; 24],
    pub m_unfiltered_throttle: f64,
    pub m_unfiltered_brake: f64,
    /// -1.0 (full left) to 1.0 (full right).
    pub m_unfiltered_steering: f64,
    _pad412: [u8; 112],
    /// Litres.
    pub m_fuel: f64,
    pub m_engine_max_rpm: f64,
    _pad540: [u8; 60],
    /// Zero-based, with the pit lane stored in the sign bit.
    pub m_current_sector: i32,
    _pad604: [u8; 4],
    /// Litres.
    pub m_fuel_capacity: f64,
    _pad616: [u8; 129],
    pub m_lap_invalidated: u8,
    _pad746: [u8; 30],
    /// LMU extension, `f32` not `f64`: remaining virtual energy as a fraction.
    pub m_virtual_energy: f32,
    /// LMU extension: seconds to the car ahead on track, published per frame.
    pub m_time_gap_car_ahead: f32,
    /// LMU extension: seconds to the car behind on track.
    pub m_time_gap_car_behind: f32,
    _pad788: [u8; 60],
    /// FL, FR, RL, RR.
    pub m_wheel: [TelemWheelV01; 4],
}

/// `VehicleScoringInfoV01` — one per car, 5 Hz.
#[repr(C, packed(4))]
#[derive(Clone, Copy)]
pub struct VehicleScoringInfoV01 {
    pub m_id: i32,
    pub m_driver_name: [u8; 32],
    pub m_vehicle_name: [u8; 64],
    pub m_total_laps: i16,
    /// 0 = sector 3 (start/finish), 1 = sector 1, 2 = sector 2.
    pub m_sector: i8,
    _pad103: [u8; 1],
    /// Metres travelled along the lap.
    pub m_lap_dist: f64,
    _pad112: [u8; 32],
    pub m_best_lap_time: f64,
    _pad152: [u8; 16],
    pub m_last_lap_time: f64,
    _pad176: [u8; 20],
    pub m_is_player: u8,
    _pad197: [u8; 1],
    pub m_in_pits: u8,
    /// 1-based overall position.
    pub m_place: u8,
    pub m_vehicle_class: [u8; 32],
    pub m_time_behind_next: f64,
    pub m_laps_behind_next: i32,
    pub m_time_behind_leader: f64,
    pub m_laps_behind_leader: i32,
    _pad256: [u8; 208],
    pub m_time_into_lap: f64,
    pub m_estimated_lap_time: f64,
    _pad480: [u8; 104],
}

/// `ScoringInfoV01` — the session header that precedes the per-car array.
#[repr(C, packed(4))]
#[derive(Clone, Copy)]
pub struct ScoringInfoV01 {
    pub m_track_name: [u8; 64],
    pub m_session: i32,
    pub m_current_et: f64,
    pub m_end_et: f64,
    pub m_max_laps: i32,
    /// **Track length in metres** — the denominator for normalised track
    /// position. Note the name collides with the per-car `m_lap_dist`, which
    /// is progress *along* this.
    pub m_lap_dist: f64,
    _pad96: [u8; 8],
    pub m_num_vehicles: i32,
    pub m_game_phase: u8,
    _pad109: [u8; 439],
}

// Sizes are the load-bearing part of the transcription: if a pad is wrong, the
// struct is the wrong size and this fails at compile time rather than silently
// decoding garbage in a race.
const _: () = assert!(std::mem::size_of::<TelemWheelV01>() == 260);
const _: () = assert!(std::mem::size_of::<TelemInfoV01>() == 1_888);
const _: () = assert!(std::mem::size_of::<VehicleScoringInfoV01>() == 584);
const _: () = assert!(std::mem::size_of::<ScoringInfoV01>() == 548);

/// Decode one transcribed struct out of a byte buffer at `offset`.
///
/// The reader itself copies straight from the mapping; this is how a byte dump
/// (the golden layout fixture, or a future capture) is read back through the
/// same transcription.
pub fn read_struct<T: Copy>(bytes: &[u8], offset: usize) -> Option<T> {
    let size = std::mem::size_of::<T>();
    let end = offset.checked_add(size)?;
    if end > bytes.len() {
        return None;
    }
    // SAFETY: bounds are checked above, `T: Copy` is one of the packed
    // transcripts (plain old data, no invalid bit patterns, alignment 4 or
    // less), and the read is unaligned so an arbitrary offset is fine.
    Some(unsafe { bytes.as_ptr().add(offset).cast::<T>().read_unaligned() })
}

/// Trim a fixed-width C string field to a `String`.
pub fn c_str(bytes: &[u8]) -> String {
    let end = bytes.iter().position(|&b| b == 0).unwrap_or(bytes.len());
    String::from_utf8_lossy(&bytes[..end]).into_owned()
}

// -------------------------------------------------------------- the reader

/// One decimated copy of the parts of the mapping we use.
pub struct Snapshot {
    pub telem: TelemInfoV01,
    pub scoring: ScoringInfoV01,
    /// Only the first `num_vehicles` entries are populated.
    pub vehicles: Vec<VehicleScoringInfoV01>,
    pub num_vehicles: usize,
    pub player_idx: usize,
    pub player_has_vehicle: bool,
}

impl Snapshot {
    /// Assemble a snapshot from already-decoded parts — how a replay or a
    /// layout test builds one without a running game.
    pub fn from_parts(
        telem: TelemInfoV01,
        scoring: ScoringInfoV01,
        vehicles: Vec<VehicleScoringInfoV01>,
    ) -> Self {
        let num_vehicles = vehicles.len().min(MAX_VEHICLES);
        let mut all = vehicles;
        all.resize(MAX_VEHICLES, unsafe { std::mem::zeroed() });
        Snapshot {
            telem,
            scoring,
            vehicles: all,
            num_vehicles,
            player_idx: 0,
            player_has_vehicle: num_vehicles > 0,
        }
    }

    fn new() -> Self {
        Snapshot {
            // SAFETY: both are plain old data with no padding invariants and no
            // Drop; all-zero is a valid (if meaningless) bit pattern, and every
            // field is overwritten before the snapshot is read.
            telem: unsafe { std::mem::zeroed() },
            scoring: unsafe { std::mem::zeroed() },
            vehicles: vec![unsafe { std::mem::zeroed() }; MAX_VEHICLES],
            num_vehicles: 0,
            player_idx: 0,
            player_has_vehicle: false,
        }
    }

    /// The player's scoring row, matched by the telemetry slot id rather than
    /// by index: the two arrays are written by different subsystems and are not
    /// guaranteed to be in the same order.
    pub fn player_scoring(&self) -> Option<&VehicleScoringInfoV01> {
        let id = self.telem.m_id;
        self.vehicles[..self.num_vehicles]
            .iter()
            .find(|v| v.m_id == id)
            .or_else(|| {
                self.vehicles[..self.num_vehicles]
                    .iter()
                    .find(|v| v.m_is_player != 0)
            })
    }

    pub fn vehicles(&self) -> &[VehicleScoringInfoV01] {
        &self.vehicles[..self.num_vehicles]
    }
}

/// What a wait on the game returned.
pub enum Wake {
    /// The game published an update.
    Event,
    /// The wait expired without an update — the sim is paused, in the menus,
    /// or wedged. Counted as a gap.
    Timeout,
    /// The game process exited.
    GameExited,
}

/// The `LMU_Data` reader: handles, the lock, and the preallocated destination
/// buffers. One of these lives on the shared-memory thread.
pub struct Reader {
    _map: OwnedHandle,
    view: MappedView,
    data_event: OwnedHandle,
    process: Option<OwnedHandle>,
    lock: SharedMemoryLock,
    snapshot: Snapshot,
}

// SAFETY: the handles and the mapped view are process-wide kernel objects, and
// `Reader` owns its destination buffers outright. It is moved onto the reader
// thread at startup and never shared, so `Send` is all that is needed.
unsafe impl Send for Reader {}

impl Reader {
    /// Open the mapping, or say precisely why we cannot.
    ///
    /// This is the one place that decides what "LMU is up" means, and the
    /// distinction it draws is the whole reason the error is split in two: a
    /// missing process is [`Error::LmuNotRunning`], while a running process
    /// with no mapping is [`Error::LmuPluginsDisabled`] — which no amount of
    /// retrying will fix, because it needs a settings change and a restart.
    pub fn open() -> Result<Self> {
        let pid = find_game_pid().ok_or(Error::LmuNotRunning)?;

        // Open-only, never create: if the section does not exist, the game is
        // not publishing, and creating it ourselves would fake a live link.
        let map =
            OwnedHandle(unsafe { OpenFileMappingW(FILE_MAP_READ, 0, wide(MAP_NAME).as_ptr()) });
        if map.0.is_null() {
            return Err(Error::LmuPluginsDisabled);
        }
        let addr = unsafe { MapViewOfFile(map.0, FILE_MAP_READ, 0, 0, LAYOUT_SIZE) };
        if addr.is_null() {
            return Err(Error::Api(format!(
                "LMU_Data mapping could not be viewed (win32 error {})",
                unsafe { GetLastError() }
            )));
        }
        let view = MappedView {
            addr,
            len: LAYOUT_SIZE,
        };

        let data_event =
            OwnedHandle(unsafe { OpenEventW(SYNCHRONIZE, 0, wide(DATA_EVENT_NAME).as_ptr()) });
        if data_event.0.is_null() {
            return Err(Error::LmuPluginsDisabled);
        }

        // The process handle is what turns a crash into a clean shutdown rather
        // than an infinite wait. It is best-effort: LMU runs under EasyAntiCheat
        // and may refuse the handle, in which case the timeout path below still
        // notices the game is gone, one poll interval later.
        let process = {
            let h = OwnedHandle(unsafe { OpenProcess(SYNCHRONIZE, 0, pid) });
            if h.0.is_null() {
                log::debug!("LMU process handle unavailable; falling back to timeout liveness");
                None
            } else {
                Some(h)
            }
        };

        Ok(Reader {
            _map: map,
            view,
            data_event,
            process,
            lock: SharedMemoryLock::open()?,
            snapshot: Snapshot::new(),
        })
    }

    /// Is the game still publishing? Cheap enough for the timeout path.
    pub fn still_running() -> bool {
        find_game_pid().is_some()
    }

    /// Block until the game publishes an update, the game exits, or `timeout`
    /// elapses. No lock is taken here — this is the cheap side of the
    /// decimation, and it runs at the game's full ~100 Hz.
    pub fn wait(&self, timeout: Duration) -> Wake {
        let millis = timeout.as_millis().min(u128::from(INFINITE - 1)) as u32;
        match &self.process {
            Some(proc) => {
                let handles = [self.data_event.0, proc.0];
                match unsafe { WaitForMultipleObjects(2, handles.as_ptr(), 0, millis) } {
                    x if x == WAIT_OBJECT_0 => Wake::Event,
                    x if x == WAIT_OBJECT_0 + 1 => Wake::GameExited,
                    _ => Wake::Timeout,
                }
            }
            None => match unsafe { WaitForSingleObject(self.data_event.0, millis) } {
                x if x == WAIT_OBJECT_0 => Wake::Event,
                x if x == WAIT_TIMEOUT && !Self::still_running() => Wake::GameExited,
                _ => Wake::Timeout,
            },
        }
    }

    /// Take the lock, memcpy the slices we use, release. Returns how long the
    /// lock was held.
    ///
    /// **Everything inside the critical section is a `copy_nonoverlapping` or
    /// an integer read.** No conversion, no allocation, no logging, no `Vec`
    /// growth — the lock is shared with the game's own writer, and time spent
    /// here is time the sim's physics thread can spend blocked.
    pub fn read(&mut self) -> Result<Duration> {
        // The unsafe block below is bounded by the layout constants, so the
        // view has to be at least that big. Checked here rather than assumed,
        // and outside the lock so it costs the game nothing.
        if self.view.len < LAYOUT_SIZE {
            return Err(Error::Api(format!(
                "LMU_Data is {} bytes, expected at least {LAYOUT_SIZE} — the game's struct layout has changed",
                self.view.len
            )));
        }
        let base = self.view.addr as *const u8;
        let started = Instant::now();
        if !self.lock.acquire(LOCK_TIMEOUT) {
            return Err(Error::Api(
                "timed out waiting for the LMU shared memory lock".into(),
            ));
        }

        // SAFETY: `base` is a view of at least LAYOUT_SIZE bytes (asserted by
        // the mapping call), and every read below is bounded by the layout
        // constants, which the const asserts above tie to the struct sizes.
        // `num` and `idx` are clamped before they are used as offsets.
        unsafe {
            let scoring = base.add(OFF_SCORING);
            std::ptr::copy_nonoverlapping(
                scoring,
                (&mut self.snapshot.scoring as *mut ScoringInfoV01).cast::<u8>(),
                SCORING_INFO_SIZE,
            );
            let num = (self.snapshot.scoring.m_num_vehicles.max(0) as usize).min(MAX_VEHICLES);
            std::ptr::copy_nonoverlapping(
                scoring.add(OFF_VEH_ARRAY),
                self.snapshot.vehicles.as_mut_ptr().cast::<u8>(),
                num * VEH_SIZE,
            );

            let telemetry = base.add(OFF_TELEMETRY);
            let active = *telemetry.add(OFF_ACTIVE_VEHICLES);
            let idx = (*telemetry.add(OFF_PLAYER_IDX) as usize).min(MAX_VEHICLES - 1);
            std::ptr::copy_nonoverlapping(
                telemetry.add(OFF_TELEM_ARRAY + idx * TELEM_SIZE),
                (&mut self.snapshot.telem as *mut TelemInfoV01).cast::<u8>(),
                TELEM_SIZE,
            );

            self.snapshot.num_vehicles = num;
            self.snapshot.player_idx = idx;
            self.snapshot.player_has_vehicle = active > 0;
        }

        self.lock.release();
        Ok(started.elapsed())
    }

    pub fn snapshot(&self) -> &Snapshot {
        &self.snapshot
    }
}

/// How long to wait for the game's lock before giving up on a frame. The game
/// holds it for microseconds; anything near this means it is wedged, and
/// dropping one frame beats blocking the reader thread forever.
const LOCK_TIMEOUT: u32 = 50;

/// The game's own cross-process lock: a two-word spin lock in its own tiny
/// mapping, with an auto-reset event as the sleep path.
///
/// Transcribed from `SharedMemoryLock` in the shipped header, with one
/// deliberate deviation — see [`SharedMemoryLock::acquire`].
struct SharedMemoryLock {
    _map: OwnedHandle,
    view: MappedView,
    event: OwnedHandle,
}

impl SharedMemoryLock {
    fn open() -> Result<Self> {
        // Create-or-open, as the header's own sample does: whichever of the
        // game and a reader starts first owns the section.
        let map = OwnedHandle(unsafe {
            CreateFileMappingW(
                INVALID_HANDLE_VALUE,
                std::ptr::null_mut(),
                PAGE_READWRITE,
                0,
                8,
                wide(LOCK_MAP_NAME).as_ptr(),
            )
        });
        if map.0.is_null() {
            return Err(Error::Api(
                "could not open the LMU shared memory lock".into(),
            ));
        }
        let existed = unsafe { GetLastError() } == ERROR_ALREADY_EXISTS;
        let addr = unsafe { MapViewOfFile(map.0, FILE_MAP_ALL_ACCESS, 0, 0, 8) };
        if addr.is_null() {
            return Err(Error::Api(
                "could not map the LMU shared memory lock".into(),
            ));
        }
        let view = MappedView { addr, len: 8 };
        let event = OwnedHandle(unsafe {
            CreateEventW(std::ptr::null_mut(), 0, 0, wide(LOCK_EVENT_NAME).as_ptr())
        });
        if event.0.is_null() {
            return Err(Error::Api("could not open the LMU lock event".into()));
        }
        let lock = SharedMemoryLock {
            _map: map,
            view,
            event,
        };
        if !existed {
            // We created it, so nobody holds it. (If the game were already up it
            // would have created it first, so this is the cold-start case.)
            lock.waiters().store(0, Ordering::Relaxed);
            lock.busy().store(0, Ordering::Relaxed);
        }
        Ok(lock)
    }

    // LockData { volatile LONG waiters; volatile LONG busy; }
    fn waiters(&self) -> &AtomicI32 {
        // SAFETY: the view is 8 bytes of shared memory holding two 4-byte
        // words; AtomicI32 has the same layout as LONG and the game touches
        // them only with interlocked operations.
        unsafe { &*(self.view.addr as *const AtomicI32) }
    }

    fn busy(&self) -> &AtomicI32 {
        unsafe { &*((self.view.addr as *const u8).add(4) as *const AtomicI32) }
    }

    /// Spin, then sleep on the event, exactly like the game's writer.
    ///
    /// Deliberate deviation from the shipped sample: its wait path returns
    /// `true` when the event fires *without* having won the compare-exchange,
    /// and leaves `waiters` incremented forever. Copying that would hand out
    /// the lock to two readers at once and leak a wakeup on every contention,
    /// so this loops until the CAS actually succeeds and always balances the
    /// counter.
    fn acquire(&self, timeout_ms: u32) -> bool {
        const MAX_SPINS: u32 = 4_000;
        for _ in 0..MAX_SPINS {
            if self.try_take() {
                return true;
            }
            std::hint::spin_loop();
        }
        self.waiters().fetch_add(1, Ordering::AcqRel);
        let deadline = Instant::now() + Duration::from_millis(u64::from(timeout_ms));
        let acquired = loop {
            if self.try_take() {
                break true;
            }
            let left = deadline.saturating_duration_since(Instant::now());
            if left.is_zero() {
                break false;
            }
            unsafe { WaitForSingleObject(self.event.0, left.as_millis() as u32) };
        };
        self.waiters().fetch_sub(1, Ordering::AcqRel);
        acquired
    }

    fn try_take(&self) -> bool {
        self.busy()
            .compare_exchange(0, 1, Ordering::Acquire, Ordering::Relaxed)
            .is_ok()
    }

    fn release(&self) {
        self.busy().store(0, Ordering::Release);
        if self.waiters().load(Ordering::Acquire) > 0 {
            unsafe { SetEvent(self.event.0) };
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Diagnostic against a running session: dumps the raw LMU-extension float
    /// block around `mVirtualEnergy`, so a field that is always zero can be
    /// told apart from one we are reading at the wrong offset or sign.
    ///
    /// `cargo test -p pf_core --lib -- --ignored --nocapture shm_live_gap_block`
    #[test]
    #[ignore = "needs Le Mans Ultimate running in a session"]
    fn shm_live_gap_block() {
        let mut reader = Reader::open().expect("open LMU_Data");
        println!("  place  cars |  ve@776  ahead@780 behind@784 place_a@788 place_b@792");
        let mut seen = 0;
        while seen < 12 {
            if !matches!(reader.wait(Duration::from_secs(3)), Wake::Event) {
                println!("(no update event)");
                continue;
            }
            if reader.read().is_err() {
                continue;
            }
            let snap = reader.snapshot();
            let telem = snap.telem;
            // Read the neighbourhood raw: the header order after mVirtualEnergy
            // is CarAhead, CarBehind, PlaceAhead, PlaceBehind, all f32.
            let bytes = unsafe {
                std::slice::from_raw_parts(
                    (&telem as *const TelemInfoV01).cast::<u8>(),
                    std::mem::size_of::<TelemInfoV01>(),
                )
            };
            let f = |off: usize| -> f32 { read_struct::<f32>(bytes, off).unwrap_or(f32::NAN) };
            let place = snap.player_scoring().map(|p| p.m_place);
            println!(
                "  {:>5?} {:>5} | {:8.4} {:9.3} {:9.3} {:11.3} {:11.3}",
                place,
                snap.num_vehicles,
                f(776),
                f(780),
                f(784),
                f(788),
                f(792)
            );
            seen += 1;
            std::thread::sleep(Duration::from_millis(300));
        }
    }

    #[test]
    fn c_str_stops_at_the_nul_not_the_end_of_the_field() {
        let mut field = [0u8; 32];
        field[..4].copy_from_slice(b"LMP3");
        field[10] = b'X'; // garbage past the terminator, as real fields carry
        assert_eq!(c_str(&field), "LMP3");
    }

    #[test]
    fn a_field_with_no_terminator_still_decodes() {
        assert_eq!(c_str(&[b'a'; 4]), "aaaa");
    }
}
